const fs = require('fs');
const path = require('path');

const env = process.env;

const environment = {
  production: true,
  apiBase: env.NG_APP_API_BASE || '/api',
  canvasWidth: parseInt(env.NG_APP_CANVAS_WIDTH || '2000', 10),
  canvasHeight: parseInt(env.NG_APP_CANVAS_HEIGHT || '2000', 10),
  rateLimitSeconds: parseInt(env.NG_APP_RATE_LIMIT_SECONDS || '30', 10)
};

const envDir = path.join(__dirname, '../src/environments');
if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
}

const envFile = path.join(envDir, 'environment.ts');
const content = `// This file is auto-generated by scripts/generate-env.js
// To customize, set environment variables: NG_APP_API_BASE, NG_APP_CANVAS_WIDTH, NG_APP_CANVAS_HEIGHT, NG_APP_RATE_LIMIT_SECONDS
export const environment = {
  production: ${environment.production},
  apiBase: '${environment.apiBase}',
  canvasWidth: ${environment.canvasWidth},
  canvasHeight: ${environment.canvasHeight},
  rateLimitSeconds: ${environment.rateLimitSeconds}
};
`;

fs.writeFileSync(envFile, content, 'utf8');
console.log('Generated environment.ts with values:', JSON.stringify(environment, null, 2));

