-- liquibase formatted sql

-- changeset maxpri:1762806348968-1
CREATE TABLE pixels
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    x         INTEGER                                  NOT NULL,
    y         INTEGER                                  NOT NULL,
    color     INTEGER                                  NOT NULL,
    placed_at TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_pixels PRIMARY KEY (id)
);

-- changeset maxpri:1762806348968-2
CREATE TABLE users
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nickname       VARCHAR(255)                             NOT NULL,
    pixel_count    BIGINT DEFAULT 0                         NOT NULL,
    last_placed_at TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset maxpri:1762806348968-3
ALTER TABLE users
    ADD CONSTRAINT uc_users_nickname UNIQUE (nickname);

