// This file is auto-generated by scripts/generate-env.js
// To customize, set environment variables: NG_APP_API_BASE, NG_APP_CANVAS_WIDTH, NG_APP_CANVAS_HEIGHT, NG_APP_RATE_LIMIT_SECONDS
export const environment = {
  production: false,
  apiBase: 'http://localhost:8080',
  canvasWidth: 2000,
  canvasHeight: 2000,
  rateLimitSeconds: 1
};
